#!/bin/bash
help(){
        cat <<EOF 
        usage ts_reset_panel [OPTION]
        -h                      prints this message
        -u [USERNAME]           specify the user whose panels will be reset,
			        defaults to the user running the command.
        -p /path/to/mountpoint  The directory where the target file system is
                                 mounted. Use this if you are working on an 
                                 externally mounted  drive 


	Resets xfce panels to their default state. 
        Only works with Xubuntu 12.04
EOF
}

# source common functions
FUNCTIONS=ts_functions.sh # /path/to../
source $FUNCTIONS

### MAIN ###

### process options ###

while getopts ":hu:p:" option; do
        case $option in
                h) help
                   exit 0
                ;;
                u) user=$OPTARG
		;;
                p) path="$OPTARG"
                ;;
                \?) help
                    exit 1
                ;;
        esac
done

#set/check user
if [[ -z $user ]]; then
    user=$USER
elif ! test_for_root; then
	echo "Could not proceed"
    echo "are you root?"
    exit 3
elif ! test_for_user $user $path; then
    echo "$user not found! exiting..."
   	exit 3
fi

pgrep xfce4 >> /dev/null
if [[ $? ==  0 && $user  == $USER]]; then
    echo "You can not run this program if you are logged in as the user"
    echo "you are attempting to change while xfce4 (the graphic environment"
    echo " is running"
    exit 4 
if

# reset panel second stage maybe unnecessary need to test

# set appropriate command and options
 

# see ticket #32682

